// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/alphabet/challange/progress': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/alphabet/challange/progress.put').default>>>>
    }
    '/api/alphabet/challange/progress/:profileId': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/alphabet/challange/progress/[profileId].get').default>>>>
    }
    '/api/auth/**:all': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/[...all]').default>>>>
    }
    '/api/debug-auth': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/debug-auth').default>>>>
    }
    '/api/profile': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/profile/index.post').default>>>>
    }
    '/api/reward/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/reward/[id].delete').default>>>>
    }
    '/api/reward': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/reward/index.post').default>>>>
    }
    '/api/reward/profile/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/reward/profile/[id].get').default>>>>
    }
    '/api/state': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/state').default>>>>
    }
    '/api/sync/alphabet': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/sync/alphabet').default>>>>
    }
    '/api/sync': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/sync/index').default>>>>
    }
    '/api/sync/profile': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/sync/profile').default>>>>
    }
    '/api/sync/rewards': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/sync/rewards').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+nitro-server@4.4.2_@b_27dd5666f0570f2656c4050f95d00806/node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
    '/_ipx/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+image@2.0.0_db0@0.3.4_c431e0a9023360ac55e80e6ef3a3feb6/node_modules/@nuxt/image/dist/runtime/server/routes/_ipx').default>>>>
    }
  }
}
export {}