name = "abelma"
compatibility_date = "2024-03-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "abelma"
database_name = "abelma"
database_id = "19bd7224-986f-441c-8bba-8b898e33b0e4"
migrations_dir = "drizzle"
