# This is an example configuration file
# To learn more, see the full config.yaml reference: https://docs.continue.dev/reference

name: my conf
version: 1.0.0
schema: v1

# Define which models can be used
# https://docs.continue.dev/customization/models
models:
  - name: QWEN3.5
    provider: llama.cpp
    model: Qwen3.5:9B
    apiBase: http://localhost:8080
    roles:
      - chat
      - edit
      - apply

# MCP Servers that Continue can access
# https://docs.continue.dev/customization/mcp-tools
mcpServers:
  - uses: anthropic/memory-mcp
